FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

# Next.js telemetry disable (optional but good for local dev)
ENV NEXT_TELEMETRY_DISABLED 1

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
