FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

# Generate prisma client before copying all code
COPY prisma ./prisma/
RUN DATABASE_URL="postgresql://dummy:dummy@dummy:5432/dummy" npx prisma generate

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]
